"""device nights

Revision ID: 01b00c4f7410
Revises: 1e0f75f6188b
Create Date: 2026-02-05 09:22:25.814458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b00c4f7410'
down_revision = '1e0f75f6188b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('night',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('night', sa.Date(), nullable=True),
    sa.Column('uploaded_started_at', sa.DateTime(), nullable=True),
    sa.Column('photo_count', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name=op.f('fk_night_device_id_device')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_night'))
    )
    with op.batch_alter_table('night', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_night_night'), ['night'], unique=False)

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('label')

    with op.batch_alter_table('night', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_night_night'))

    op.drop_table('night')
    # ### end Alembic commands ###
