"""devices

Revision ID: 1e0f75f6188b
Revises: fa1a14e3e62b
Create Date: 2025-11-20 12:05:29.190847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e0f75f6188b'
down_revision = 'fa1a14e3e62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('upload_key', sa.String(), nullable=True),
    sa.Column('former_keys', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device'))
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_upload_key'), ['upload_key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_upload_key'))
        batch_op.drop_index(batch_op.f('ix_device_name'))

    op.drop_table('device')
    # ### end Alembic commands ###
