"""night last_modified

Revision ID: 288d7b30d84a
Revises: 01b00c4f7410
Create Date: 2026-03-05 09:57:32.041792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288d7b30d84a'
down_revision = '01b00c4f7410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('night', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_modified', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('night', schema=None) as batch_op:
        batch_op.drop_column('last_modified')

    # ### end Alembic commands ###
