"""Storage subdir and antenna name

Revision ID: 4e0563f8bbee
Revises: 919d96aa02b3
Create Date: 2026-08-05 12:00:30.999273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e0563f8bbee'
down_revision = '919d96aa02b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('antenna_deployment_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True))
        batch_op.add_column(sa.Column('storage_subdir', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('storage_subdir')
        batch_op.drop_column('antenna_deployment_name')

    # ### end Alembic commands ###
