"""device last_refreshed

Revision ID: 4eb6d149f67d
Revises: 288d7b30d84a
Create Date: 2026-03-05 11:14:21.838768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb6d149f67d'
down_revision = '288d7b30d84a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_refreshed', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('last_refreshed')

    # ### end Alembic commands ###
