"""night config from s3

Revision ID: 6cb477380297
Revises: b554b3406871
Create Date: 2026-05-04 08:32:44.779244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb477380297'
down_revision = 'b554b3406871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('night', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('night', schema=None) as batch_op:
        batch_op.drop_column('config')

    # ### end Alembic commands ###
