"""device version

Revision ID: 8649bb17a51f
Revises: bc543b03ae44
Create Date: 2026-03-31 12:48:18.343824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8649bb17a51f'
down_revision = 'bc543b03ae44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_version', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True))
        batch_op.add_column(sa.Column('recent_logs', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('recent_logs')
        batch_op.drop_column('code_version')

    # ### end Alembic commands ###
