"""Antenna ids

Revision ID: 919d96aa02b3
Revises: 6cb477380297
Create Date: 2026-05-19 10:25:58.058711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919d96aa02b3'
down_revision = '6cb477380297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('antenna_deployment', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('antenna_last_synced', sa.DateTime(), nullable=True))

    with op.batch_alter_table('night', schema=None) as batch_op:
        batch_op.add_column(sa.Column('antenna_event', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('night', schema=None) as batch_op:
        batch_op.drop_column('antenna_event')

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('antenna_last_synced')
        batch_op.drop_column('antenna_deployment')

    # ### end Alembic commands ###
