"""retired device

Revision ID: 953f7e161430
Revises: 4e0563f8bbee
Create Date: 2026-09-17 09:53:03.995692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953f7e161430'
down_revision = '4e0563f8bbee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retired', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('retired')

    # ### end Alembic commands ###
