"""night last_photo

Revision ID: b36a1d95bb67
Revises: 8649bb17a51f
Create Date: 2026-04-15 12:54:34.853443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b36a1d95bb67'
down_revision = '8649bb17a51f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('night', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_photo', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('night', schema=None) as batch_op:
        batch_op.drop_column('last_photo')

    # ### end Alembic commands ###
