"""user site devices

Revision ID: b554b3406871
Revises: b36a1d95bb67
Create Date: 2026-04-24 23:42:43.909861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b554b3406871'
down_revision = 'b36a1d95bb67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_site_devices',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name=op.f('fk_user_site_devices_device_id_device')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_site_devices_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'device_id', name=op.f('pk_user_site_devices'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_site_devices')
    # ### end Alembic commands ###
