"""device config

Revision ID: bc543b03ae44
Revises: 4eb6d149f67d
Create Date: 2026-03-24 12:43:14.307619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc543b03ae44'
down_revision = '4eb6d149f67d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remote_config', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('updated_config', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('updated_config')
        batch_op.drop_column('remote_config')

    # ### end Alembic commands ###
